### ISSUE TITLE
auto build (cuisine) for G8OS

### ISSUE THREAD

**Issue by despiegk** [g8os/home#11]
see

https://github.com/g8os/builder

phase 1
- build kernel (through docker)
- build arch x64 and create tgz
  - this tgz should install through our cuisine module
- push to our pub gig reflectors https://github.com/g8os/home/issues/10
- push the binaries over rsync to same reflector (allow easy update of stick)

**Comment by grimpy** [comment]
Building is done.
Upload still need tbd

**Comment by zaibon** [comment]
not relevant anymore
