### ISSUE TITLE
use openvswitch for networking in g8os

### ISSUE THREAD

**Issue by despiegk** [g8os/home#12]

**Comment by muhamadazmy** [comment]
@despiegk 
Do we just need to start openvswitch services (db and vswitch) or we need to do more than that? Who I should contact for details ?

**Comment by despiegk** [comment]
???

**Comment by muhamadazmy** [comment]
Currently the core can do the following:
- It starts required ovs services
- It creates `tap` devices as configured in the network.toml file
- It brings up configured interfaces

After  that, network bootstrapping continues as normal. Core tries to reach controller over the configured bridges until it can reach

More information about the configurations can be found here https://gig.gitbooks.io/g8os/content/docs/config/network.html

**Comment by grimpy** [comment]
@despiegk please provided input or close
