### ISSUE TITLE
creation of the flist for gig-engine components

### ISSUE THREAD

**Issue by zaibon** [g8os/home#20]
- [ ] plain ubuntu 16.04
- [ ] ardb server with rocksdb backend
- [ ] ardb server with forestdb backend

**Comment by maxux** [comment]
- [x] plain ubuntu 16.04: http://home.maxux.net/gig/flist-ubuntu1604.db.tar.gz
- [x] ardb server with rocksdb backend: http://home.maxux.net/gig/flist-ardb-rocksdb.db.tar.gz
- [x] ardb server with forestdb backend: http://home.maxux.net/gig/flist-ardb-forestdb.db.tar.gz
