### ISSUE TITLE
Archive obsolete repositories to GOGS

### ISSUE THREAD

**Issue by FastGeert** [g8os/home#24]
Lets keep this clean

**Comment by zaibon** [comment]
repo moved :
- https://docs.greenitglobe.com/archive/grakoon
- https://docs.greenitglobe.com/archive/ays_openvstorage
- https://docs.greenitglobe.com/archive/stor
- https://docs.greenitglobe.com/archive/corectl
- https://docs.greenitglobe.com/archive/ipfsregistry
- https://docs.greenitglobe.com/archive/g8os_fs
