### ISSUE TITLE
fix performance issue in FS

### ISSUE THREAD

**Issue by despiegk** [g8os/home#3]
FS is too slow
it should max be 50% slower than native (but in fact I think can be much better)

test in R & RW mode

**Comment by iwanbk** [comment]
@despiegk @muhamadazmy 
From my quick using `dd`, FS is slower between 35%-45%.

Below is `top10` result from  pprof
```
(pprof) top10   
170ms of 180ms total (94.44%)
Showing top 10 nodes out of 53 (cum >= 10ms)
      flat  flat%   sum%        cum   cum%
      70ms 38.89% 38.89%      100ms 55.56%  syscall.Syscall
      20ms 11.11% 50.00%       20ms 11.11%  runtime.(*mspan).sweep.func1
      10ms  5.56% 55.56%       10ms  5.56%  runtime.(*mcentral).grow
      10ms  5.56% 61.11%       10ms  5.56%  runtime.casgstatus
      10ms  5.56% 66.67%       10ms  5.56%  runtime.getcallerpc
      10ms  5.56% 72.22%       10ms  5.56%  runtime.lock
      10ms  5.56% 77.78%       10ms  5.56%  runtime.memmove
      10ms  5.56% 83.33%       20ms 11.11%  runtime.rawstring
      10ms  5.56% 88.89%       30ms 16.67%  runtime.slicebytetostring
      10ms  5.56% 94.44%       10ms  5.56%  runtime/internal/atomic.Cas
```
The first two columns show the number of samples in which the function was running (as opposed to waiting for a called function to return), as a raw count and as a percentage of total samples.
So, `syscall.Syscall`, `runtime.(*mspan).sweep.func1` , `runtime.(*mcentral).grow` are top three functions that take the time.

`sweep` is GC action, while `grow` is memory/heap allocation.
I guest syscall is calling file related system call.

Next step:
- test using more sophisticated tools like `iozone` or `fio`
- check for GC & memory related improvement

**Comment by despiegk** [comment]
its not about iozone or fio
because that is to 1 file
that is not where the issue is

issue is when opening lots of files
e.g. when we walk over filesystem
even when files are in cache already


On Mon, Feb 29, 2016 at 10:15 AM, Iwan Budi Kusnanto <
notifications@github.com> wrote:

> @despiegk <https://github.com/despiegk> @muhamadazmy
> <https://github.com/muhamadazmy>
> From my quick using dd, FS is slower between 35%-45%.
>
> Below is top10 result from pprof
>
> (pprof) top10
> 170ms of 180ms total (94.44%)
> Showing top 10 nodes out of 53 (cum >= 10ms)
>       flat  flat%   sum%        cum   cum%
>       70ms 38.89% 38.89%      100ms 55.56%  syscall.Syscall
>       20ms 11.11% 50.00%       20ms 11.11%  runtime.(*mspan).sweep.func1
>       10ms  5.56% 55.56%       10ms  5.56%  runtime.(*mcentral).grow
>       10ms  5.56% 61.11%       10ms  5.56%  runtime.casgstatus
>       10ms  5.56% 66.67%       10ms  5.56%  runtime.getcallerpc
>       10ms  5.56% 72.22%       10ms  5.56%  runtime.lock
>       10ms  5.56% 77.78%       10ms  5.56%  runtime.memmove
>       10ms  5.56% 83.33%       20ms 11.11%  runtime.rawstring
>       10ms  5.56% 88.89%       30ms 16.67%  runtime.slicebytetostring
>       10ms  5.56% 94.44%       10ms  5.56%  runtime/internal/atomic.Cas
>
> The first two columns show the number of samples in which the function was
> running (as opposed to waiting for a called function to return), as a raw
> count and as a percentage of total samples.
> So, syscall.Syscall, runtime.(*mspan).sweep.func1 ,
> runtime.(*mcentral).grow are top three functions that take the time.
>
> sweep is GC action, while grow is memory/heap allocation.
> I guest syscall is calling file related system call.
>
> Next step:
>
>    - test using more sophisticated tools like iozone or fio
>    - check for GC & memory related improvement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g8os/home/issues/3#issuecomment-190115469>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by iwanbk** [comment]
```
issue is when opening lots of files
```
iozone can also do multithreading test.
using iozone to do write test with 5 threads, FS is +90% slower than native.

profiling give different results
```
30ms 60.00% 60.00%       30ms 60.00%  syscall.Syscall
      10ms 20.00% 80.00%       10ms 20.00%  path/filepath.Clean
      10ms 20.00%   100%       10ms 20.00%  runtime.(*mcentral).grow
         0     0%   100%       50ms   100%  github.com/Jumpscale/aysfs/watcher.(*backenCleaner).Run
         0     0%   100%       40ms 80.00%  os.Lstat
         0     0%   100%       10ms 20.00%  path/filepath.Join
         0     0%   100%       50ms   100%  path/filepath.Walk
         0     0%   100%       10ms 20.00%  path/filepath.join
         0     0%   100%       50ms   100%  path/filepath.walk
         0     0%   100%       10ms 20.00%  runtime.(*mcache).refill
```
I am starting to check the code now

@despiegk what test tools you use? so we don't missed any check.

**Comment by iwanbk** [comment]
After more `iozone` tests, i found that it is slower by at least 95%.

I have tried to replace file.WriteAt  (https://github.com/g8os/fs/blob/master/rw/file.go#L183)  usage with bufio, but it didn't give any improvement.
I was thinking of optimizing write func because i thought this is where the syscall being called.

I got more detailed profiling graph from iozone & dd test,  and found that:
- Cleaner goroutine was the one that dominating the profiling result
- Cleaner goroutine only run for < 1 second
A bit weird, it is quite fast but dominating the result.

So, i will check it again without running the cleaner.

I attached profiling graph

from iozone
![pprof-iozone](https://cloud.githubusercontent.com/assets/977552/13417496/2ac7b0ce-df9f-11e5-9dcb-25f9bd284fc6.jpg)

from dd
![pprof-dd](https://cloud.githubusercontent.com/assets/977552/13417523/5939f8cc-df9f-11e5-9c6e-3758fdbeab6b.jpg)

**Comment by iwanbk** [comment]
@despiegk @muhamadazmy 
Please forget about my test result that stated it slower by 90-95% using iozone.
The test was using this command
```
iozone -t 5 -i 0 -F 1 2 3 4 5
```
It only writes 512kb of files.

I changed to make it write 100mb of files using this command
```
iozone -l 5 -u 5 -r 4k -s 100mm -F 1 2 3 4 5 -i 0
```
The performance is slower by around 75% now, using 5 threads.

I think i have more accurate profiling result, please see these attachments.
[profile-dd-2gb.pdf](https://github.com/g8os/home/files/152176/profile-dd-2gb.pdf)
[profile-iozone-100mb-without-cleaner.pdf](https://github.com/g8os/home/files/152177/profile-iozone-100mb-without-cleaner.pdf)

As you can see, most time was used by bazil, our fuse library.

I think it is worth to do these:
- check bazil implementation
- try another lib, maybe https://github.com/hanwen/go-fuse, it is native binding.

**Comment by muhamadazmy** [comment]
I was thinking idd we should try another library

**Comment by zaibon** [comment]
Other library is an idea indeed. But I liked the fact that this one if fully written in Go. I also found the interface of hanwen/go-fuse more cumbersome than the one from bazil/fuse.

Maybe it worst looking a bit in the implementation of bazil/fuse, I remember @robvanmieghem saying that he didn't had this slow issue on Mac at all.  Means issue probably come from a linux implementation detail in the lib ??

**Comment by iwanbk** [comment]
```
Maybe it worst looking a bit in the implementation of bazil/fuse
```
OK, wiil check it.

```
I remember @robvanmieghem saying that he didn't had this slow issue on Mac at all
```
I thought g8os/fs doesn't support Mac, it failed to build for me.
```
~/pathgo/src/github.com/g8os/fs#go build ./...
# github.com/g8os/fs/watcher
watcher/cleaner.go:38: sys.Atim undefined (type *syscall.Stat_t has no field or method Atim)
watcher/cleaner.go:38: not enough arguments in call to time.Unix
~/pathgo/src/github.com/g8os/fs#go version
go version go1.6 darwin/amd64
~/pathgo/src/github.com/g8os/fs#
```

**Comment by despiegk** [comment]
it has not to do with performance on 1 file (see my remark before)
so tools like iozone won't tell you much

we are particularly slow when we work when opening lots of small files
please write a benchmark prog for that

e.g. use the RW feature, write lots of small files
same for R feature , open all files & read them see why slow
compare with same test on native FS



k.

On Tue, Mar 1, 2016 at 10:44 AM, Iwan Budi Kusnanto <
notifications@github.com> wrote:

> Maybe it worst looking a bit in the implementation of bazil/fuse
>
> OK, wiil check it.
>
> I remember @robvanmieghem saying that he didn't had this slow issue on Mac at all
>
> I thought g8os/fs doesn't support Mac, it failed to build for me.
>
> ~/pathgo/src/github.com/g8os/fs#go build ./...
> # github.com/g8os/fs/watcher
> watcher/cleaner.go:38 <http://github.com/g8os/fs/watcherwatcher/cleaner.go:38>: sys.Atim undefined (type *syscall.Stat_t has no field or method Atim)
> watcher/cleaner.go:38: not enough arguments in call to time.Unix
> ~/pathgo/src/github.com/g8os/fs#go version
> go version go1.6 darwin/amd64
> ~/pathgo/src/github.com/g8os/fs#
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g8os/home/issues/3#issuecomment-190575784>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
@iwanbk it used to build on mac, I can see the build fails on a `linux` specific code (recent code). This part should be adopted to support mac as well, I don't have mac to test build and performance on it.

**Comment by iwanbk** [comment]
```
it has not to do with performance on 1 file (see my remark before)
so tools like iozone won't tell you much
```
I saw your remark, but `iozone` has multi processes option.
```
iozone -t 10 -r 4k -s 100mm  -i 0
```
With this command, it will create 10 processes, each process write to different file.

I will write the benchmark prog anyway (after checking bazel fuse & native binding), so we can see it.

**Comment by iwanbk** [comment]
**profiling**
i did more check on profiling result and found that after calling bazel/fuse code, it going back to call `github.com/g8os/fs/rw.(*fsFileHandle).Write` func.

So, it use our own Go code to write file.

**bazel/fuse**
I can't find any flaw in the code, i will do more check tomorrow and then check `github.com/hanwen/go-fuse`

**testing**
I did iozone test using various number of processes, here are my finding

`native`
number of process - write speed - read speed
1      722628     4587816
2      265395    2621656
4     45664       1361901
8     10485       3537             -> very dropped read speed

`fuse`
1 44516   325428
2  20608  219381
4  9958    102366
8 5077    3464                     -> very dropped read speed

From above test, read speed was very dropped in 8 processes, but it also happens in native FS. So, we still can't conclude that it has scalability issue.
But it really has speed issue.

**Comment by iwanbk** [comment]
I have checked hanwen/go-fuse lib:
- From my understanding, it only has advantage of using native libfuse to dispatch file operation request to our own handler
- from previous profiling graph, our own handler is where the slowness come.
- their example also use file.WriteAt to write to file, same as current implementation.
@muhamadazmy CMIIW in case you also have checked hanwen/go-fuse.

So, i think it is better to improve what we have now.

**Comment by iwanbk** [comment]
test result using program from PR https://github.com/g8os/fs/pull/3
command : `benchmark -nf=20,50,100 -sf=2`
The command means : Write & read 2 MB of files, using 20, 50, and 100 goroutines. Each goroutine write/read to different file.

Time is total execution time
**native**
```
#files 	 write time 	 read time
20 		 3.791748675s 	 10.961196ms
50 		 9.504657191s 	 22.045919ms
100 		 19.003215961s 	 46.899218ms
```
Performance is quite consistent

**fuse**
```
#files 	 write time 	 read time
20 		 4.010416167s 	 87.938237ms
50 		 9.85989628s 	 282.545306ms
100 		 19.741489371s 	 5.754063046s
```
Performance is dropped when using 100 goroutines.(100 goroutines is a lot of files btw)

It also sometimes make the fuse crashed.

**Comment by iwanbk** [comment]
i updated test result in previous comment, it use improved benchmark program.

**Comment by iwanbk** [comment]
profiling result for above tests
[profile-read-write.pdf](https://github.com/g8os/home/files/154634/profile-read-write.pdf)

Focusing on read operation, majority of the times spent on `bazil.org/fuse.(*ReadRequest).Respond `
From my quick check, it seems that it is the code which copy/move read result from fuse to our application.
I said `move` because from profiling it use `runtime.memmove`

**Comment by iwanbk** [comment]
fixed in PR https://github.com/g8os/fs/pull/10

**Comment by despiegk** [comment]
@rkhamis please find someone to do proper tests and make sure all newest code is used

**Comment by grimpy** [comment]
Verfified by @ashraffouda
