### ISSUE TITLE
architecture diagram

### ISSUE THREAD

**Issue by despiegk** [g8os/home#4]
make nice pic in gdoc & expose as png
which gets linked to docs

**Comment by muhamadazmy** [comment]
[Sequence Diagram](http://www.plantuml.com/plantuml/img/NL9DZnCn3BtdL_W84imFMAb8PSMA5Mn158bBBsxYpaJDs2F7NJJyUfpfTa1xYkAyZxoNMBP2i9D4y574gYbEK-O-X32XMevvGZQu5pQLKaW1AyHNPqfjYY5iDl38sJAM_0Sj2yDc4qAlSfbWH_PRz0p7PkCk0U7z1y0x-2gOWCawax44B0O_TOOep1IRHWCwCjwzceF9WUDwiK2b4ZnWBfJyw0PSRHev3N42Ps8f1yvif7p2IDLd1CUvBJUPKeuOpojxMslk6HGvoGZLF5s4n-_W-uFVO8O1DKMlCVaq42Vti6LTqeUkwvPwFZkX3dYcrimYxhds3VUqlG_nnUqJHvsd9UGNcWEB4SXpApyyoSKxfol0tHxsSAdjmMmWK3BDzEpZCyrriM_SrUW7lRHovK2jvOfS73JtWuLVc0rEebxWEBRRmaazClR45hQBeevOG2RIvOrhzy-enVIKkolasmtImluVOc_-Vy0_HK8QNG7Ur3gy0xBe0czNkRy0)

**Comment by muhamadazmy** [comment]
[Gdoc](https://docs.google.com/a/codescalers.com/document/d/1VrmHY830FGRCmqzrJysVr2U1oElThfsy-UaNsmS49zQ/edit?usp=sharing)

**Comment by despiegk** [comment]
can expose as png
& then put picture on markdown page


On Sun, Feb 28, 2016 at 11:31 AM, Muhamad Azmy <notifications@github.com>
wrote:

> Gdoc
> <https://docs.google.com/a/codescalers.com/document/d/1VrmHY830FGRCmqzrJysVr2U1oElThfsy-UaNsmS49zQ/edit?usp=sharing>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g8os/home/issues/4#issuecomment-189837296>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
https://gig.gitbooks.io/g8os/content/intro.html
