### ISSUE TITLE
first docu for g8os

### ISSUE THREAD

**Issue by despiegk** [g8os/home#5]
use the gitbooks repo
https://www.gitbook.com/book/gig/g8os

create working set of docu
- how to get started
- how to use
- configuration
- ...

**Comment by despiegk** [comment]
a lot of content can be moved from main jumpscale repo 
e.g. https://gig.gitbooks.io/jumpscale8/content/BeyondBasics/AYS%20FS.html

**Comment by muhamadazmy** [comment]
Main configuration
https://gig.gitbooks.io/g8os/content/docs/config/generic.html
Network configuration
https://gig.gitbooks.io/g8os/content/docs/config/network.html

**Comment by despiegk** [comment]
@muhamadazmy documentation around network is not clear, please fix asap.
e.g. how is relation with OpenvSwitch, when used when not, ...?

**Comment by grimpy** [comment]
OpenvSwitch deamon and database are always started when they are configured (with ovs-vsctl) their devices will be configured before the network.toml is processed. From within the network.toml file one can add IP layer on top of those devices.
