### ISSUE TITLE
bootstrap os 0.9

### ISSUE THREAD

**Issue by despiegk** [g8os/home#8]
first version of our  boostrap os
- use existing OS
- let a lot still be local (just to win time)
- we need tools to do this automatically & the output needs to be a tgz which can be expanded on USB stick or any VM
- we need support for arm based devices (pi) & 64bit machines

for install need something like
- https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/cuisine_/CuisineInstaller.py#L646

all needs to get into
- https://github.com/g8os/builder/tree/master

starting points, examples, ...

**Comment by despiegk** [comment]
some specs
https://github.com/g8os/home/blob/master/specs/sandboxing.md

**Comment by despiegk** [comment]
@zaibon @muhamadazmy how far are we here
documentation how to build
example scripts in the repo?

**Comment by despiegk** [comment]
@muhamadazmy make sure we have KVM tools, libvirt, docker tools, openvswitch, mc, ...

**Comment by muhamadazmy** [comment]
sure

**Comment by grimpy** [comment]
Please add documentation and close
